### ISSUE TITLE
LivePlot does not allow selection of .db database

### ISSUE THREAD

**Issue by nfortune** [pyplotter/pyplotter#13]
I am able to select a _database folder_ using the database explorer (as well as select and plot a completed run - nice! ) BUT am not able to select an _individual database_  such as LivePlotTest.db  from LivePlot menu >  Open LivePlot > Select Database. All the individual files in a folder remain greyed out. 

I am running Mac OS 14.5 and QCoDeS 0.45.0. per instructions, I have pyplotter installed in a separate Conda environment from QCoDeS.

**Comment by edumur** [comment]
Hi,

What you describe sounds like the expected behavior of the plotter.
You can browse folders on the top left table and open databases by clicking on them.
The selected database will them display its content on the bottom table.

**Comment by nfortune** [comment]
Yes, that part works . It is the live plot option that doesn’t work. You
have an animated gif showing use of the live plot dialog box to select a
database from a list of files in a folder . That is the part that doesn’t
work.

Professor Nathanael Fortune
315 McConnell Hall
44 College Lane
Smith College
Northampton MA 01063

https://www.smith.edu/academics/faculty/nathanael-fortune
<http://www.smith.edu/physics/>

(413) 585-3980 (office)
(413) 585-3919 (lab)
***@***.***

gendered pronouns: he/him/his

*"The drilling in the wall kept up but no one seemed to pay it any mind...
<https://www.bobdylan.com/songs/lily-rosemary-and-jack-hearts/>" --- Bob
Dylan*

*from Lily, Rosemary, and the Jack of Hearts (Blood on the Tracks) *

**Comment by edumur** [comment]
It is working locally for me.
Are you sure you chose, from the main menu bar, Liveplot -> Open Liveplot and then click on the button " select database"?

**Comment by nfortune** [comment]
Yes, I am attempting to do that in the manner shown in the animated gif. I
will look to see if this is an issue with using python 3.12 instead of 3.11
and/or Mac OS instead of windows, then get back to you.

PS: the select default directory option for live plot also doesn’t seem to
have any effect.  Again, just live plot.

**Comment by nfortune** [comment]
database selection using LivePlot dialog box works in Windows 10 but not in
Mac OS 14.5, so somehow the database files ending in .db are not being
recognized as legitimate selections. They appear but are all grayed out and
can not be selected. I can provide more details if you let me know what
information would be helpful.

The LivePlot has different errors on my Windows 10 installation. It opens a
window but doesn't autoscale and doesn't detect the updates to the database
cache. Eventually the whole program freezes.  Again, I can provide more
details if you let me know what information would be helpful.

In comparison, Plottr does collect and display live data properly (after a
5 - 10 second delay launching) on Windows.  I can't get it to launch at all
on Mac OS. Something to do with Qt settings but I can't figure it out.

Except for the LivePlot, your PyPlotter program works very nicely on Mac OS
and seems much easier to use/ more capable than Plottr. I would love to be
able to use PyPlotter for the live plotting as well. Right now I have no
live plotting options for QCoDeS on mac os.

best regards,

Nat Fortune

PS: Plottr,  PyPlotter, and QCoDes are installed in their own conda
environments for both the WIndows and Mac OS systems.

Professor Nathanael Fortune
315 McConnell Hall
44 College Lane
Smith College
Northampton MA 01063

https://www.smith.edu/academics/faculty/nathanael-fortune
<http://www.smith.edu/physics/>

(413) 585-3980 (office)
(413) 585-3919 (lab)
***@***.***

gendered pronouns: he/him/his

*"The drilling in the wall kept up but no one seemed to pay it any mind...
<https://www.bobdylan.com/songs/lily-rosemary-and-jack-hearts/>" --- Bob
Dylan*

*from Lily, Rosemary, and the Jack of Hearts (Blood on the Tracks) *

**Comment by edumur** [comment]
Hi,

Many thing to discuss, I tried to sort it out below:
1. I found indeed a mistake in the case of 2d plot preventing the update of the data. Now it is as for 1d plot (normally).
2. The liveplot as an autoscale option, did you enable it?
3. I tried to fix the open db issue on mac . Tell me if that changes anything for you

**Comment by nfortune** [comment]
1. not yet tested code fix (1) on windows. Will investigate.
   2. autoscale option enabled
   3. open db issue on mac not fixed for Liveplot. Clicking on 'modify
   database' button in Liveplot dialog box allows you to navigate to folder of
   your choice but still will not allow selection of .db files (or any files,
   for that matter) within that folder.  See screenshot below
   4. results not affected by choice of python 3.11 or 3.12
   5. can successfully select and display completed runs using pyplotter
   'data explorer' but errors are reported in terminal:


(pyplotter) ***@***.*** ~ % plotter


qt.qpa.fonts: Populating font family aliases took 55 ms. Replace uses of
missing font family "MS Shell Dlg 2" with one that exists to avoid this
cost.


TypeError: invalid result from TableWidgetDatabase.eventFilter(), a 'bool'
is expected not 'NoneType'


Painter path exceeds +/-32767 pixels.


qt.qpa.backingstore: Back buffer dpr of 2 doesn't match
<NSViewBackingLayer: 0x6000031a5560> contents scale of 1 - updating layer
to match.
Professor Nathanael Fortune
315 McConnell Hall
44 College Lane
Smith College
Northampton MA 01063

https://www.smith.edu/academics/faculty/nathanael-fortune
<http://www.smith.edu/physics/>

(413) 585-3980 (office)
(413) 585-3919 (lab)
***@***.***

gendered pronouns: he/him/his

*"The drilling in the wall kept up but no one seemed to pay it any mind...
<https://www.bobdylan.com/songs/lily-rosemary-and-jack-hearts/>" --- Bob
Dylan*

*from Lily, Rosemary, and the Jack of Hearts (Blood on the Tracks) *

**Comment by edumur** [comment]
I am afraid I will not be able to do much more related to your issues on macOs as I can't make test locally...

Please keep me posted on your issue on windows.

Ps: when you post error message, put them in a code block so that they are easy to read.

**Comment by nfortune** [comment]
There is a workaround to select a qcodes .db database on MacOS (tested on 14.5): 

1. choose open LivePlot from the LivePlot menu 
2.  click on 'select database'
3.  click on the desired database, which should allow you to then select/open that database for LivePlot (but doesn't) 
4.  right click or Control-click on the .db database and choose `Quick Look`
5. you can now select/open that database for LivePlot

**Comment by nfortune** [comment]
Using workaround, LivePlot launches but graphs do not update: 

1. first time a run is executed in Qcodes, Liveplot opens window and autoscales with first set of data from cache but never updates with new data
2. second time a run is executed in Qcodes,  window is opened but will not autoscale, will not display data, will not update. 

Here are errors reported in terminal window: 


```
qt.qpa.fonts: Populating font family aliases took 49 ms. Replace uses of missing font family "MS Shell Dlg 2" with one that exists to avoid this cost. 

Painter path exceeds +/-32767 pixels.
Painter path exceeds +/-32767 pixels.
Trying to mark a run completed that was already completed.
Trying to mark a run completed that was already completed.
Trying to mark a run completed that was already completed.

```

Here is qcodes code used to generate plots and errors: 
```
import os

import numpy as np

import qcodes as qc
from qcodes.dataset import (
    Measurement,
    do1d,
    initialise_or_create_database_at,
    load_or_create_experiment,
)
from qcodes.instrument_drivers.mock_instruments import (
    DummyInstrument,
    DummyInstrumentWithMeasurement,
)

qc.logger.start_all_logging()

dac = DummyInstrument('dac', gates=['ch1', 'ch2'])
dmm = DummyInstrumentWithMeasurement(name='dmm', setter_instr=dac)

station = qc.Station(dmm, dac)

db_file_path = os.path.join(os.getcwd(), 'NewLivePlotTest.db')
initialise_or_create_database_at(db_file_path)
exp = load_or_create_experiment(experiment_name='NewLivePlotTest',
                          sample_name="no sample")

do1d(dac.ch1, 0, 25, 100, 0.5, dmm.v1, dmm.v2, write_period=0.1)

```

**Comment by nfortune** [comment]
following error occurs in pyplotter LivePlot on WIndows: 

`TypeError: invalid result from TableWidgetDatabase.eventFilter(), a 'bool' is expected not 'NoneType'`

qcodes is same as above

**Comment by nfortune** [comment]
This sequence causes liveplot error on Windows using PyPlotter 0.3.7 

1. 1st terminal window (Anaconda Prompt)
```
conda activate qcodes
(qcodes) Jupyter notebook
....run same qcodes code as before 
```

2. new terminal window: 

```
conda activate --stack pyplotter
(pyplotter) plotter 
```
3. select database in LivePlot dialog box 
3. launch run in qcodes

`do1d(dac.ch1, 0, 25, 50, 0.5, dmm.v1, dmm.v2, write_period=0.1, do_plot=False)`
4. result: everything works within qcodes
5. test plotting of completed run in pyplotter: everything works
6. open liveplot dialog box, specify database, launch new run in qcodes

`do1d(dac.ch1, 0, 25, 50, 0.5, dmm.v1, dmm.v2, write_period=0.1, do_plot=False)`

6. LivePlot opens window, scales, does not update.
7. clicking autoscale button in lower left causes it to update once, then freezes. 
`Error message:  (pyplotter) Trying to mark a run completed that was already completed`
8. launch new run in qcodes, graph opens but does not plot data, no autoscaling. Error message repeats
9. launch 3rd new run in qcodes
10. plot window opens, no data shown, no autoscaling, asking for autoscaling generates this error

```
Traceback:
File "C:\Users\goodfortunelab\pyplotter\plyplotter\ui\plot\plot1d\widgetPlot1d.py", line 574,
 in comboBoxXAxisActivated self.plotItem.setLabel(axis = 'bottom', 
UnboundLocalError: cannot access local variable 'newXLabel' where it is not associated with a value

Trying to mark a run completed that was already completed. 
```

**Comment by edumur** [comment]
Hi,

I found some error while using the doNd function from qcodes by using your code.
Thanks for that.

Your example now works for me.
Please try the fix and keep me posted.

**Comment by nfortune** [comment]
What is the Recommended install process for these fixes?  Latest release is
listed as 0.3.7 . Thanks !

Professor Nathanael Fortune
315 McConnell Hall
44 College Lane
Smith College
Northampton MA 01063

https://www.smith.edu/academics/faculty/nathanael-fortune
<http://www.smith.edu/physics/>

(413) 585-3980 (office)
(413) 585-3919 (lab)
***@***.***

gendered pronouns: he/him/his

*"The drilling in the wall kept up but no one seemed to pay it any mind...
<https://www.bobdylan.com/songs/lily-rosemary-and-jack-hearts/>" --- Bob
Dylan*

*from Lily, Rosemary, and the Jack of Hearts (Blood on the Tracks) *

**Comment by edumur** [comment]
I just pushed a 0.3.8 for you.

**Comment by nfortune** [comment]
Sorry to be dense but I don’t see it. How do I access version 0.3.8 ?

Professor Nathanael Fortune
315 McConnell Hall
44 College Lane
Smith College
Northampton MA 01063

https://www.smith.edu/academics/faculty/nathanael-fortune
<http://www.smith.edu/physics/>

(413) 585-3980 (office)
(413) 585-3919 (lab)
***@***.***

gendered pronouns: he/him/his

*"The drilling in the wall kept up but no one seemed to pay it any mind...
<https://www.bobdylan.com/songs/lily-rosemary-and-jack-hearts/>" --- Bob
Dylan*

*from Lily, Rosemary, and the Jack of Hearts (Blood on the Tracks) *

**Comment by edumur** [comment]
The upgraded version is already on github.
you can follow the readme for the installation:
First you create the conda environement

```
conda create --name pyplotter python=3.11
conda activate pyplotter
```
Second, install packages with conda
`
conda install pyqtgraph`


Third, install pyplotter
```

git clone https://github.com/pyplotter/pyplotter
cd pyplotter
pip install -e .
```

**Comment by nfortune** [comment]
OK, but when I do as instructed above, I still get version 0.3.7

```
Obtaining file:///C:/Users/goodfortunelab/pyplotter
uninstalling pyplotter-0.3.7:
successfully uninstalled pyplotter-0.3.7
successfully installed pyplotter-0.3.7
'''

I do see that here several changes are listed for 0.3.8: 
https://github.com/pyplotter/pyplotter/commit/0c0907ce369ec9b5986dd12c8a7459710ffb2c5e

but  on the right hand column of https://github.com/pyplotter/pyplotter, under Releases, 

GitHub still claims the most recent release is 0.3.7 from March 5t.

Theinstructions provided appear to download that version. 

I am not a GitHub expert, so perhaps I am missing something obvious that I need to do differently, sorry!

**Comment by edumur** [comment]
I would then update your local repo by typing:
```
git pull
```

**Comment by nfortune** [comment]
good news -- 0.3.8 now works on my local Window OS  when running do1d qcode routine I shared earlier.  Will check on Mac OS next.

**Comment by nfortune** [comment]
partial good news --LivePlot now works in pyplotter version 0.3.8 on Mac OS 14.5 if use the 'Quick Look' workaround I shared earlier (to enable selection of a particular .db database using the LivePlot dialog box).  Tested using same qcodes do1d routine as on Windows. 

I would like to retry the Mac OS file selection fix you added then removed to see if it now works as well (as it could be the files weren't really updating before git pull). How would I do that? Thanks!

**Comment by edumur** [comment]
No problem.
It's done, please try.

**Comment by nfortune** [comment]
alas, it didn't fix the database selection bug in LivePlot. That said, there is a reliable if quirky workaround: 

1. right click or control click and select QUICK LOOK once the LivePlot file selection dialog box opens. 
2. Close the Quick Look info box. This  enables file selection. 
3. select the desired .db database

I'm going to close this issue for now since I have a working solution now and no idea how to change the code to eliminate the need for a workaround.  A seasoned Mac OS programmer might have an idea how to eliminate the need for the workaround and want to reopen it to propose a fix.
